//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MasterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Master", Namespace="http://schemas.datacontract.org/2004/07/MyGames.Model")]
    [System.SerializableAttribute()]
    public partial class Master : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentStaminaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentXPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxStaminaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxXPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OnlineCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaminaCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentStamina {
            get {
                return this.CurrentStaminaField;
            }
            set {
                if ((this.CurrentStaminaField.Equals(value) != true)) {
                    this.CurrentStaminaField = value;
                    this.RaisePropertyChanged("CurrentStamina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentXP {
            get {
                return this.CurrentXPField;
            }
            set {
                if ((this.CurrentXPField.Equals(value) != true)) {
                    this.CurrentXPField = value;
                    this.RaisePropertyChanged("CurrentXP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MId {
            get {
                return this.MIdField;
            }
            set {
                if ((this.MIdField.Equals(value) != true)) {
                    this.MIdField = value;
                    this.RaisePropertyChanged("MId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MLevel {
            get {
                return this.MLevelField;
            }
            set {
                if ((this.MLevelField.Equals(value) != true)) {
                    this.MLevelField = value;
                    this.RaisePropertyChanged("MLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MName {
            get {
                return this.MNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MNameField, value) != true)) {
                    this.MNameField = value;
                    this.RaisePropertyChanged("MName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxStamina {
            get {
                return this.MaxStaminaField;
            }
            set {
                if ((this.MaxStaminaField.Equals(value) != true)) {
                    this.MaxStaminaField = value;
                    this.RaisePropertyChanged("MaxStamina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxXP {
            get {
                return this.MaxXPField;
            }
            set {
                if ((this.MaxXPField.Equals(value) != true)) {
                    this.MaxXPField = value;
                    this.RaisePropertyChanged("MaxXP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OnlineCount {
            get {
                return this.OnlineCountField;
            }
            set {
                if ((this.OnlineCountField.Equals(value) != true)) {
                    this.OnlineCountField = value;
                    this.RaisePropertyChanged("OnlineCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaminaCount {
            get {
                return this.StaminaCountField;
            }
            set {
                if ((this.StaminaCountField.Equals(value) != true)) {
                    this.StaminaCountField = value;
                    this.RaisePropertyChanged("StaminaCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.syfri.cn", ConfigurationName="MasterService.MasterService")]
    public interface MasterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syfri.cn/MasterService/Register", ReplyAction="http://www.syfri.cn/MasterService/RegisterResponse")]
        int Register(string account, string pwd, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syfri.cn/MasterService/Create", ReplyAction="http://www.syfri.cn/MasterService/CreateResponse")]
        int Create(string accountId, string masterName, int race, int professional, int sex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syfri.cn/MasterService/GetMasterById", ReplyAction="http://www.syfri.cn/MasterService/GetMasterByIdResponse")]
        Client.MasterService.Master GetMasterById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syfri.cn/MasterService/Logon", ReplyAction="http://www.syfri.cn/MasterService/LogonResponse")]
        bool Logon(string accountName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MasterServiceChannel : Client.MasterService.MasterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterServiceClient : System.ServiceModel.ClientBase<Client.MasterService.MasterService>, Client.MasterService.MasterService {
        
        public MasterServiceClient() {
        }
        
        public MasterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Register(string account, string pwd, string email) {
            return base.Channel.Register(account, pwd, email);
        }
        
        public int Create(string accountId, string masterName, int race, int professional, int sex) {
            return base.Channel.Create(accountId, masterName, race, professional, sex);
        }
        
        public Client.MasterService.Master GetMasterById(string id) {
            return base.Channel.GetMasterById(id);
        }
        
        public bool Logon(string accountName, string password) {
            return base.Channel.Logon(accountName, password);
        }
    }
}
